platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '0.15.0'
pod 'Async', :git => 'https://github.com/duemunk/Async.git', :commit => 'abe23c1'
pod 'RealmSwift', '0.95.2'
pod 'Kingfisher', '1.6'
pod 'TUSafariActivity', '1.0.4'
pod 'LarryBird', :git => 'https://github.com/d6u/LarryBird.git', :tag => 'v0.0.4'
pod 'RxSwift', '1.9.0'
pod 'RxCocoa', '1.9.0'
pod 'EasyAnimation', '1.0.1'
pod 'DZNEmptyDataSet', '1.7'
pod 'M13ProgressSuite', '1.2.7'
pod 'BRYXBanner', '0.2.2'
pod 'AsyncDisplayKit', '1.2.3'
