import UIKit

let UNREAD_COUNT_BACKGROUND_COLOR = UIColor(netHex: 0x888888)
let TWEET_CELL_TEXT_WIDTH = screenBounds().width - 72 - 10
let TWEET_CELL_IMAGE_BOX_HEIGHT = ceil(TWEET_CELL_TEXT_WIDTH / 2)

let BLUE = UIColor(netHex: 0x549AE6)
